#!/usr/bin/env bash
# run-m0-baseline.sh — M0 milestone harness (issue #1).
#
# Drives the m0-cluster deployment end to end:
#   for each storm node: kernel nvme-tcp connect from the initiator host,
#   data-path verify (write/readback), fio baselines (4k randrw, 4k randread,
#   1M seq read, 1M seq write), disconnect.
# Results land in docs/m0-baseline.md.
#
# Prereqs: deploy/terragrunt/m0-cluster applied (see its header), VMs booted.
# Usage:   deploy/m0/run-m0-baseline.sh
# Env:     STORM_NODES / INITIATOR to override the default IPs;
#          FIO_RUNTIME (seconds per fio job, default 20).
#
# Repeatable as a forcicd job: apply -> this script -> destroy.
#
# NOTE: this harness drives nvme-tcp by hand to validate the raw data path.
# In production the attach flow is stormblock-csi calling the /v1 API
# (POST /v1/volumes/{id}/attach -> AttachInfo{nqn, addresses}); the engine
# side of making /v1 attach provision a real per-volume namespace is part
# of the #5-#7 track.

set -euo pipefail

STORM_NODES="${STORM_NODES:-storm1=192.168.8.62 storm2=192.168.8.63 storm3=192.168.8.64}"
INITIATOR="${INITIATOR:-192.168.8.65}"
FIO_RUNTIME="${FIO_RUNTIME:-20}"
NQN_PREFIX="nqn.2026-01.io.stormblock"
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_MD="$REPO_ROOT/docs/m0-baseline.md"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

SSH_OPTS="-o BatchMode=yes -o ConnectTimeout=8 -o StrictHostKeyChecking=accept-new"

ssh_init() { ssh $SSH_OPTS "root@$INITIATOR" "$@"; }

wait_port() { # host port label
    local host=$1 port=$2 label=$3 t=60
    while ! nc -z -w2 "$host" "$port" 2>/dev/null; do
        t=$((t - 1))
        [ $t -le 0 ] && { echo "FATAL: $label ($host:$port) never came up"; exit 1; }
        sleep 5
    done
    echo "  $label up ($host:$port)"
}

echo "== M0: waiting for nodes =="
for kv in $STORM_NODES; do
    ip="${kv#*=}"
    wait_port "$ip" 4420 "${kv%%=*} nvmeof"
    wait_port "$ip" 9090 "${kv%%=*} mgmt"
done
wait_port "$INITIATOR" 22 "initiator ssh"

fio_job() { # devpath name rw bs extra...
    local dev=$1 name=$2 rw=$3 bs=$4; shift 4
    ssh_init "fio --name=$name --filename=$dev --direct=1 --rw=$rw --bs=$bs \
        --ioengine=libaio --iodepth=16 --numjobs=1 --time_based --runtime=$FIO_RUNTIME \
        --group_reporting --output-format=json $*"
}

json_get() { # file jq-expr
    python3 -c "
import json, sys
d = json.load(open('$1'))
j = d['jobs'][0]
print($2)
"
}

summarize() { # jsonfile -> 'IOPS_read IOPS_write BW_read_MBps BW_write_MBps lat_p99_us_read'
    json_get "$1" "'%d %d %.1f %.1f %.0f' % ( \
        j['read']['iops'], j['write']['iops'], \
        j['read']['bw_bytes']/1e6, j['write']['bw_bytes']/1e6, \
        (j['read']['clat_ns'].get('percentile',{}).get('99.000000',0))/1000)"
}

RESULTS="$WORK/results.txt"
: > "$RESULTS"

for kv in $STORM_NODES; do
    node="${kv%%=*}"; ip="${kv#*=}"
    nqn="$NQN_PREFIX:$node"
    echo "== $node ($ip): discover + connect =="
    ssh_init "nvme discover -t tcp -a $ip -s 4420 | head -30" || true
    ssh_init "nvme connect -t tcp -a $ip -s 4420 -n $nqn"

    # Wait for the namespace device
    DEV=""
    for _ in $(seq 1 15); do
        DEV=$(ssh_init "nvme list -o json 2>/dev/null | python3 -c \"
import json,sys
d=json.load(sys.stdin)
for dev in d.get('Devices',[]):
    if 'stormblock' in (dev.get('ModelNumber','')+dev.get('SubsystemNQN','')).lower() or True:
        print(dev['DevicePath']); break
\"" 2>/dev/null) || true
        [ -n "$DEV" ] && break
        sleep 2
    done
    [ -n "$DEV" ] || { echo "FATAL: no nvme namespace appeared for $node"; exit 1; }
    SIZE=$(ssh_init "blockdev --getsize64 $DEV")
    echo "  attached: $DEV ($((SIZE / 1024 / 1024)) MB)"

    echo "== $node: data-path verify =="
    ssh_init "dd if=/dev/urandom of=/tmp/m0.pat bs=1M count=8 status=none &&
        dd if=/tmp/m0.pat of=$DEV bs=1M count=8 oflag=direct status=none &&
        dd if=$DEV of=/tmp/m0.chk bs=1M count=8 iflag=direct status=none &&
        cmp /tmp/m0.pat /tmp/m0.chk && echo VERIFY_OK"

    echo "== $node: fio baselines (${FIO_RUNTIME}s each) =="
    for job in "randrw randrw 4k --rwmixread=70" "randread randread 4k" "seqread read 1M" "seqwrite write 1M"; do
        set -- $job
        label=$1 rw=$2 bs=$3 extra="${4:-}"
        fio_job "$DEV" "$label" "$rw" "$bs" $extra > "$WORK/$node-$label.json"
        echo "$node $label $(summarize "$WORK/$node-$label.json")" >> "$RESULTS"
        echo "  $label: $(summarize "$WORK/$node-$label.json")"
    done

    ssh_init "nvme disconnect -n $nqn" >/dev/null
    echo "  disconnected"
done

echo "== writing $OUT_MD =="
{
    echo "# M0 baseline — NVMe-oF/TCP attach + fio (issue #1)"
    echo
    echo "Generated by \`deploy/m0/run-m0-baseline.sh\` on $(date -u +%Y-%m-%dT%H:%MZ)."
    echo "Topology: 3 stormblock nodes (2×10G file drives → RAID1 → 8G thin volume,"
    echo "NVMe-oF/TCP :4420) + 1 initiator host (kernel nvme-tcp), all Proxmox VMs"
    echo "(2 vCPU / 2 GB, virtio disk). Numbers are a floor, not a ceiling: file-backed"
    echo "drives on VM disks, no tuning, iodepth=16, ${FIO_RUNTIME}s per job."
    echo
    echo "| node | job | read IOPS | write IOPS | read MB/s | write MB/s | p99 read lat (µs) |"
    echo "|------|-----|-----------|------------|-----------|------------|-------------------|"
    while read -r node label riops wiops rbw wbw p99; do
        echo "| $node | $label | $riops | $wiops | $rbw | $wbw | $p99 |"
    done < "$RESULTS"
    echo
    echo "Data-path verify: 8 MB random pattern written with O_DIRECT, read back, byte-compared — per node."
    echo
    echo "**Production note:** clients never drive \`nvme connect\` by hand — attach goes"
    echo "through stormblock-csi against the \`/v1\` API (\`POST /v1/volumes/{id}/attach\` →"
    echo "\`AttachInfo{nqn, addresses}\`). This harness validates the data path underneath"
    echo "that flow; wiring \`/v1\` attach to real per-volume namespaces is the #5–#7 track."
} > "$OUT_MD"

echo "== M0 PASS =="
cat "$OUT_MD"
